#remote_theme: pmarsceill/just-the-docs

theme: jekyll-theme-minimal

title: Kateřina Kolouchová
#description:

baseurl: ""
url: "https://katkolouchova.github.io"
footer_content: "Copyright &copy; 2022 Kateřina Kolouchová. <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
last_edit_timestamp: true