remote_theme: pmarsceill/just-the-docs

title: Kateřina Kolouchová
description: About me

baseurl: ""
url: "https://katkolouchova.github.io"
footer_content: "Copyright &copy; 2020 Kateřina Kolouchová. <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
last_edit_timestamp: true


search_enabled: false